{ name = "ctl-package-example"
, dependencies =
  [ "aff"
  , "arrays"
  , "bifunctors"
  , "bytearrays"
  , "cardano-collateral-select"
  , "cardano-data-lite"
  , "cardano-hd-wallet"
  , "cardano-key-wallet"
  , "cardano-message-signing"
  , "cardano-plutus-data-schema"
  , "cardano-transaction-builder"
  , "cardano-transaction-balancer"
  , "cardano-transaction-lib"
  , "cardano-types"
  , "cip30-mock"
  , "console"
  , "control"
  , "datetime"
  , "effect"
  , "exceptions"
  , "foldable-traversable"
  , "js-bigints"
  , "js-date"
  , "maybe"
  , "monad-logger"
  , "mote"
  , "mote-testplan"
  , "noble-secp256k1"
  , "now"
  , "ordered-collections"
  , "plutus-types"
  , "posix-types"
  , "prelude"
  , "profunctor-lenses"
  , "safely"
  , "spec"
  , "strings"
  , "transformers"
  , "tuples"
  , "uplc-apply-args"
  , "uint"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "exe/**/*.purs", "test/**/*.purs" ]
}
